### ISSUE TITLE
Does this work with SADX?

### ISSUE THREAD

**Issue by Eeve2espeon** [michael-fadely/d3d8to11#10]
(cuz the SADX version says it's missing some module, and you archived it...)

**Comment by michael-fadely** [comment]
It does, yes. I test with it regularly because it has a relatively simple fixed-function pipeline. It won't work with sadx-dc-lighting unless you use the d3d11 fork, though.

**Comment by Eeve2espeon** [comment]
> It does, yes. I test with it regularly because it has a relatively simple fixed-function pipeline. It won't work with sadx-dc-lighting unless you use the d3d11 fork, though.

weird, cuz when I put the file into the mods folder, it doesn't show up in the mod manager :\ (I'm having problems with the SADX one you have on your profile) was wondering if it worked with the game, but it doesn't even show up

**Comment by michael-fadely** [comment]
It works quite differently. You should have d3d8.dll, and a folder full of shaders. The folder and the DLL go right in the root directory (where the game's executable sonic.exe is). It's quite intensive on first run, but after you get shader permutations compiled, it should run smoothly.

**Comment by Eeve2espeon** [comment]
So I basically put these files into SADX's folder, and it should run it in d3d11? but would I have to do anything extra, since I'm running it on steam?

**Comment by michael-fadely** [comment]
The vanilla Steam version runs on D3D9, and this will not work with it. But, if you already have mods installed, there's a good chance you're running the older D3D8 version, and you don't need to do anything special. Just put it all in there, and it should work.

**Comment by Eeve2espeon** [comment]
I do have mods installed, thats cuz one of the mods I'm playing mostly kinda needs D3D11 so some of the graphical features in it work, like transparency stuff. (for ex: sonic jump aura makes doors, water, and etc invisible, some textures look wrong or bright blue, etc)
I tried putting it in the programming folder, then the SADX folder itself, none of those work, and I even tried again with those two folders, but also putting on the mod made for SADX, but none of it works :\
The mod I'm talking about is the one made by Benji, the Sonic, shadow, Metal sonic one, with one of the required ones being an older version of your D3D11 mod (which doesn't even work)

**Comment by michael-fadely** [comment]
That mod will almost certainly not work with this translation layer, as it relies on APIs only present in the SADX-specific version in order to function.

**Comment by Eeve2espeon** [comment]
Sooo... I'm basically stuck with this then? Cuz the %OIT/OIT_no_text mod that was included with Benji's mod, is like an older version of the D3D11 mod, but it's more broken. Aka, the game loads the mod, but any menus, don't appear, anything with transparency doesn't load, and there are a whole bunch more graphical bugs due to it, while the new D3D11 mod says "missing module sadx-d3d11.dll"

**Comment by michael-fadely** [comment]
If the source code for their modifications to it are still available, you can still compile it and use it. Same goes for my original version.
