### ISSUE TITLE
Downloadable .dll or compile instructions

### ISSUE THREAD

**Issue by Alekc89** [michael-fadely/d3d8to11#11]
Hi, do you offer a binary or compile instructions?

**Comment by michael-fadely** [comment]
Normally builds are available on the [CI](https://ci.appveyor.com/project/michael-fadely/d3d8to11), but it appears to be broken.

I don't have build instructions written down, but it's pretty straight forward. If you're on a reasonably modern version of Windows 10 and have the DirectX SDK installed, just open up `d3d8to11.sln` with Visual Studio 2019, and build the solution (probably for x86). Copy the HLSL, HLSLI, and DLL files from the `bin` folder to your game's root directory. Just make sure to grab all the submodules first if you're cloning from git (`git submodule update --init --recursive`).

**Comment by ghost** [comment]
@michael-fadely 
Hello, I would like to second the request of the original poster. It would be of a great use for everyone interested in this project if you could provide us the binary file. Unfortunately I am not familiar with Visual Studio and I'm afraid I wouldn't be able to compile it properly.

**Comment by michael-fadely** [comment]
Hey @Mitch037, thanks for the ping; I totally forgot about this. I'll try to rectify this later today.

**Comment by michael-fadely** [comment]
Build artifacts are once again available on AppVeyor. You can download builds by going [here](https://ci.appveyor.com/project/michael-fadely/d3d8to11), clicking on a platform (usually x86 for old games), and then clicking on the Artifacts button. d3d8to11.7z should be in the list. Downloads expire in one month.

**Comment by DeathWrench** [comment]
Can you do the appveyor thing again? I've been trying to compile this for a fat minute and can't manage to do it.
